import { API_URL } from '../config/api';

export type DailyContext={id:string;date:string;timeZone:string;availableMinutes:number;priorityTaskId:string|null;blocker:string;note:string;revision:number};
export type ProposalTask={id:string;goalId:string;goalTitle:string;instruction:string;estimatedMinutes:number|null;status:'pending'|'completed'};
export type Selection={taskId:string;allocationMinutes:number};
export type AdaptiveProposal={id:string;date:string;timeZone:string;status:'ready'|'accepted'|'rejected'|'stale';availableMinutes:number;requiredMinutes:number;selected:Selection[];omittedTaskIds:string[];remainingMinutes:number;conflicts:{code:string;taskId:string|null;message:string}[];uncertainty:{code:string;taskId:string;message:string}[];currentPlanFits:boolean;eligibleTasks:ProposalTask[];explanation:{summary:string;reason:string;evidenceTaskIds:string[];question:string|null}|null};
export type ProposalResult={kind:'no_change';evaluation:Omit<AdaptiveProposal,'id'|'date'|'timeZone'|'status'|'eligibleTasks'|'explanation'>;tasks:ProposalTask[]}|{kind:'proposal';proposal:AdaptiveProposal;reused:boolean;aiFallback:boolean};

function isObject(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
function timeZone(){return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';}
async function error(response:Response){const body:unknown=await response.json().catch(()=>null);throw new Error(isObject(body)&&typeof body.error==='string'?body.error:`Request returned HTTP ${response.status}`);}
function parseProposal(value:unknown):AdaptiveProposal{if(!isObject(value)||typeof value.id!=='string'||typeof value.date!=='string'||typeof value.timeZone!=='string'||!['ready','accepted','rejected','stale'].includes(String(value.status))||typeof value.availableMinutes!=='number'||typeof value.requiredMinutes!=='number'||typeof value.remainingMinutes!=='number'||typeof value.currentPlanFits!=='boolean'||!Array.isArray(value.selected)||!Array.isArray(value.omittedTaskIds)||!Array.isArray(value.conflicts)||!Array.isArray(value.uncertainty)||!Array.isArray(value.eligibleTasks))throw new Error('Unexpected adaptive proposal');return value as AdaptiveProposal;}

export async function getDailyContext(date:string,signal:AbortSignal){const response=await fetch(`${API_URL}/daily-contexts/${encodeURIComponent(date)}?timeZone=${encodeURIComponent(timeZone())}`,{signal});if(!response.ok)await error(response);const data:unknown=await response.json();if(!isObject(data))throw new Error('Unexpected context response');return data.context===null?null:data.context as DailyContext;}
export async function saveDailyContext(date:string,input:{availableMinutes:number;priorityTaskId:string|null;blocker:string;note:string}){const response=await fetch(`${API_URL}/daily-contexts/${encodeURIComponent(date)}?timeZone=${encodeURIComponent(timeZone())}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!response.ok)await error(response);const data:unknown=await response.json();if(!isObject(data)||!isObject(data.context))throw new Error('Unexpected context response');return data.context as DailyContext;}
export async function createAdaptiveProposal(date:string,key:string){const response=await fetch(`${API_URL}/daily-plans/${encodeURIComponent(date)}/proposals?timeZone=${encodeURIComponent(timeZone())}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({includeExplanation:true})});if(!response.ok)await error(response);const data:unknown=await response.json();if(!isObject(data)||!['proposal','no_change'].includes(String(data.kind)))throw new Error('Unexpected proposal response');if(data.kind==='proposal')return {...data,proposal:parseProposal(data.proposal)} as ProposalResult;return data as ProposalResult;}
export async function editAdaptiveProposal(id:string,selected:Selection[]){const response=await fetch(`${API_URL}/plan-proposals/${encodeURIComponent(id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({selected})});if(!response.ok)await error(response);const data:unknown=await response.json();if(!isObject(data))throw new Error('Unexpected edit response');return parseProposal(data.proposal);}
export async function rejectAdaptiveProposal(id:string){const response=await fetch(`${API_URL}/plan-proposals/${encodeURIComponent(id)}/reject`,{method:'POST'});if(!response.ok)await error(response);}
export async function acceptAdaptiveProposal(id:string,key:string){const response=await fetch(`${API_URL}/plan-proposals/${encodeURIComponent(id)}/accept`,{method:'POST',headers:{'Idempotency-Key':key}});if(!response.ok)await error(response);return response.json();}
export function newIdempotencyKey(prefix:string){return `${prefix}:${Date.now()}:${Math.random().toString(36).slice(2)}`;}
