import { API_URL } from '../config/api';

export type OutcomeInput={title:string;description:string;targetValue:number|null;targetUnit:string|null;targetDate:string|null};
export type GoalOutcome=OutcomeInput&{id:string;goalId:string;outcomeType:'qualitative'|'measurable';status:'in_progress'|'achieved';revision:number};
export type GoalMilestone=OutcomeInput&{id:string;goalId:string;outcomeId:string;sequence:number;status:'not_started'|'in_progress'|'completed';revision:number};
export type OutcomeSuggestion={outcome:{title:string;description:string};milestones:{title:string;description:string;sequence:number}[]};
function object(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
async function body(response:Response){const value:unknown=await response.json().catch(()=>null);if(!response.ok)throw new Error(object(value)&&typeof value.error==='string'?value.error:`Request returned HTTP ${response.status}`);return value;}
function outcome(value:unknown):GoalOutcome{if(!object(value)||typeof value.id!=='string'||typeof value.goalId!=='string'||typeof value.title!=='string'||typeof value.description!=='string'||!['qualitative','measurable'].includes(String(value.outcomeType))||!['in_progress','achieved'].includes(String(value.status))||typeof value.revision!=='number')throw new Error('Unexpected outcome response');return value as GoalOutcome;}
function milestone(value:unknown):GoalMilestone{if(!object(value)||typeof value.id!=='string'||typeof value.goalId!=='string'||typeof value.outcomeId!=='string'||typeof value.title!=='string'||typeof value.description!=='string'||typeof value.sequence!=='number'||!['not_started','in_progress','completed'].includes(String(value.status))||typeof value.revision!=='number')throw new Error('Unexpected milestone response');return value as GoalMilestone;}
export async function getOutcome(goalId:string,signal:AbortSignal){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/outcome`,{signal}));if(!object(data))throw new Error('Unexpected outcome response');return data.outcome===null?null:outcome(data.outcome);}
export async function getMilestones(goalId:string,signal:AbortSignal){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/milestones`,{signal}));if(!object(data)||!Array.isArray(data.milestones))throw new Error('Unexpected milestones response');return data.milestones.map(milestone);}
export async function createOutcome(goalId:string,input:OutcomeInput){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/outcome`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}));return outcome(object(data)?data.outcome:null);}
export async function updateOutcome(goalId:string,input:OutcomeInput,expectedRevision:number){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/outcome`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,expectedRevision})}));return outcome(object(data)?data.outcome:null);}
export async function setOutcomeStatus(goalId:string,status:GoalOutcome['status'],expectedRevision:number){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/outcome/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,expectedRevision})}));return outcome(object(data)?data.outcome:null);}
export async function deleteOutcome(goalId:string,expectedRevision:number){await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/outcome`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision})}));}
export async function createMilestone(goalId:string,input:OutcomeInput){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/milestones`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}));return milestone(object(data)?data.milestone:null);}
export async function updateMilestone(id:string,input:OutcomeInput,expectedRevision:number){const data=await body(await fetch(`${API_URL}/milestones/${encodeURIComponent(id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,expectedRevision})}));return milestone(object(data)?data.milestone:null);}
export async function setMilestoneStatus(id:string,status:GoalMilestone['status'],expectedRevision:number){const data=await body(await fetch(`${API_URL}/milestones/${encodeURIComponent(id)}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,expectedRevision})}));return milestone(object(data)?data.milestone:null);}
export async function deleteMilestone(id:string,expectedRevision:number){await body(await fetch(`${API_URL}/milestones/${encodeURIComponent(id)}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision})}));}
export async function reorderMilestones(goalId:string,items:GoalMilestone[]){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/milestones/order`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:items.map((item)=>item.id),revisions:Object.fromEntries(items.map((item)=>[item.id,item.revision]))})}));if(!object(data)||!Array.isArray(data.milestones))throw new Error('Unexpected order response');return data.milestones.map(milestone);}
export async function suggestOutcome(goalId:string){const data=await body(await fetch(`${API_URL}/goals/${encodeURIComponent(goalId)}/outcome-suggestions`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}));if(!object(data)||!object(data.suggestion)||!object(data.suggestion.outcome)||!Array.isArray(data.suggestion.milestones))throw new Error('Unexpected suggestion response');return data.suggestion as OutcomeSuggestion;}
export async function linkTaskMilestone(taskId:string,milestoneId:string|null){await body(await fetch(`${API_URL}/tasks/${encodeURIComponent(taskId)}/milestone`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({milestoneId})}));}
