import { Router } from 'express';
import { pool } from './db.ts';
import { GroqRequestError } from './ai/groqPlanService.ts';
import { generateOutcomeSuggestion } from './outcomes/groqOutcomeService.ts';
import { OutcomeConflictError, OutcomeRepository } from './outcomes/outcomeRepository.ts';
import { LOCAL_OWNER_ID } from './outcomes/types.ts';
import { isObject, parseRevisionedInput, validateExpectedRevision, validateMilestoneInput, validateOutcomeInput } from './outcomes/validation.ts';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function validId(value:unknown):value is string{return typeof value==='string'&&uuid.test(value);}
function conflict(res:{status(code:number):{json(value:unknown):unknown}},error:unknown){if(error instanceof OutcomeConflictError){res.status(409).json({error:error.code==='stale_revision'?'This record changed. Reload before saving again.':'The relationship conflicts with current goal data.',code:error.code});return true;}return false;}

export function createOutcomeRouter(repository=new OutcomeRepository(pool),suggest=generateOutcomeSuggestion){const router=Router();
  router.get('/goals/:goalId/outcome',async(req,res)=>{if(!validId(req.params.goalId)){res.status(400).json({error:'Invalid goal ID.'});return;}try{if(!await repository.goalExists(LOCAL_OWNER_ID,req.params.goalId)){res.status(404).json({error:'Goal not found.'});return;}res.status(200).json({outcome:await repository.getOutcome(LOCAL_OWNER_ID,req.params.goalId)});}catch{res.status(500).json({error:'Could not load the outcome.'});}});
  router.post('/goals/:goalId/outcome',async(req,res)=>{if(!validId(req.params.goalId)){res.status(400).json({error:'Invalid goal ID.'});return;}try{const input=validateOutcomeInput(req.body);const outcome=await repository.createOutcome(LOCAL_OWNER_ID,req.params.goalId,input);if(!outcome){res.status(404).json({error:'Goal not found.'});return;}res.status(201).json({outcome});}catch(error){if(conflict(res,error))return;if(error instanceof Error){res.status(400).json({error:error.message});return;}res.status(500).json({error:'Could not create the outcome.'});}});
  router.put('/goals/:goalId/outcome',async(req,res)=>{if(!validId(req.params.goalId)){res.status(400).json({error:'Invalid goal ID.'});return;}try{const {input,expectedRevision}=parseRevisionedInput(req.body);const outcome=await repository.updateOutcome(LOCAL_OWNER_ID,req.params.goalId,input,expectedRevision);if(!outcome){res.status(404).json({error:'Outcome not found.'});return;}res.status(200).json({outcome});}catch(error){if(conflict(res,error))return;if(error instanceof Error){res.status(400).json({error:error.message});return;}res.status(500).json({error:'Could not update the outcome.'});}});
  router.delete('/goals/:goalId/outcome',async(req,res)=>{if(!validId(req.params.goalId)){res.status(400).json({error:'Invalid goal ID.'});return;}try{if(!isObject(req.body)||Object.keys(req.body).length!==1){res.status(400).json({error:'Provide expectedRevision.'});return;}const removed=await repository.deleteOutcome(LOCAL_OWNER_ID,req.params.goalId,validateExpectedRevision(req.body.expectedRevision));if(!removed){res.status(404).json({error:'Outcome not found.'});return;}res.status(204).end();}catch(error){if(conflict(res,error))return;if(error instanceof Error){res.status(400).json({error:error.message});return;}res.status(500).json({error:'Could not delete the outcome.'});}});
  router.post('/goals/:goalId/outcome/status',async(req,res)=>{if(!validId(req.params.goalId)||!isObject(req.body)||!['in_progress','achieved'].includes(String(req.body.status))){res.status(400).json({error:'Invalid outcome status request.'});return;}try{const outcome=await repository.setOutcomeStatus(LOCAL_OWNER_ID,req.params.goalId,req.body.status as never,validateExpectedRevision(req.body.expectedRevision));if(!outcome){res.status(404).json({error:'Outcome not found.'});return;}res.status(200).json({outcome});}catch(error){if(conflict(res,error))return;res.status(400).json({error:error instanceof Error?error.message:'Invalid request.'});}});
  router.get('/goals/:goalId/milestones',async(req,res)=>{if(!validId(req.params.goalId)){res.status(400).json({error:'Invalid goal ID.'});return;}try{if(!await repository.goalExists(LOCAL_OWNER_ID,req.params.goalId)){res.status(404).json({error:'Goal not found.'});return;}res.status(200).json({milestones:await repository.listMilestones(LOCAL_OWNER_ID,req.params.goalId)});}catch{res.status(500).json({error:'Could not load milestones.'});}});
  router.post('/goals/:goalId/milestones',async(req,res)=>{if(!validId(req.params.goalId)){res.status(400).json({error:'Invalid goal ID.'});return;}try{const milestone=await repository.createMilestone(LOCAL_OWNER_ID,req.params.goalId,validateMilestoneInput(req.body));if(!milestone){res.status(409).json({error:'Define an outcome before adding milestones.',code:'outcome_required'});return;}res.status(201).json({milestone});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Invalid milestone.'});}});
  router.put('/milestones/:id',async(req,res)=>{if(!validId(req.params.id)){res.status(400).json({error:'Invalid milestone ID.'});return;}try{const {input,expectedRevision}=parseRevisionedInput(req.body,true);const milestone=await repository.updateMilestone(LOCAL_OWNER_ID,req.params.id,input,expectedRevision);if(!milestone){res.status(404).json({error:'Milestone not found.'});return;}res.status(200).json({milestone});}catch(error){if(conflict(res,error))return;res.status(400).json({error:error instanceof Error?error.message:'Invalid milestone.'});}});
  router.delete('/milestones/:id',async(req,res)=>{if(!validId(req.params.id)||!isObject(req.body)){res.status(400).json({error:'Invalid deletion request.'});return;}try{const removed=await repository.deleteMilestone(LOCAL_OWNER_ID,req.params.id,validateExpectedRevision(req.body.expectedRevision));if(!removed){res.status(404).json({error:'Milestone not found.'});return;}res.status(204).end();}catch(error){if(conflict(res,error))return;res.status(400).json({error:error instanceof Error?error.message:'Invalid request.'});}});
  router.post('/milestones/:id/status',async(req,res)=>{if(!validId(req.params.id)||!isObject(req.body)||!['not_started','in_progress','completed'].includes(String(req.body.status))){res.status(400).json({error:'Invalid milestone status request.'});return;}try{const milestone=await repository.setMilestoneStatus(LOCAL_OWNER_ID,req.params.id,req.body.status as never,validateExpectedRevision(req.body.expectedRevision));if(!milestone){res.status(404).json({error:'Milestone not found.'});return;}res.status(200).json({milestone});}catch(error){if(conflict(res,error))return;res.status(400).json({error:error instanceof Error?error.message:'Invalid request.'});}});
  router.put('/goals/:goalId/milestones/order',async(req,res)=>{if(!validId(req.params.goalId)||!isObject(req.body)||!Array.isArray(req.body.ids)||!isObject(req.body.revisions)||!req.body.ids.every(validId)){res.status(400).json({error:'Invalid milestone order.'});return;}try{const milestones=await repository.reorderMilestones(LOCAL_OWNER_ID,req.params.goalId,req.body.ids,req.body.revisions as Record<string,number>);res.status(200).json({milestones});}catch(error){if(conflict(res,error))return;res.status(400).json({error:'Could not reorder milestones.'});}});
  router.put('/tasks/:taskId/milestone',async(req,res)=>{if(!validId(req.params.taskId)||!isObject(req.body)||!(req.body.milestoneId===null||validId(req.body.milestoneId))){res.status(400).json({error:'Invalid task milestone link.'});return;}try{const task=await repository.linkTask(LOCAL_OWNER_ID,req.params.taskId,req.body.milestoneId as string|null);if(!task){res.status(404).json({error:'Task not found.'});return;}res.status(200).json({task});}catch(error){if(conflict(res,error))return;res.status(500).json({error:'Could not link the task.'});}});
  router.post('/goals/:goalId/outcome-suggestions',async(req,res)=>{if(!validId(req.params.goalId)||!isObject(req.body)||Object.keys(req.body).length>0){res.status(400).json({error:'Invalid suggestion request.'});return;}try{const goal=await pool.query<{goal:string;description:string}>('SELECT title AS goal,reason AS description FROM public.goals WHERE id=$1 AND owner_id=$2',[req.params.goalId,LOCAL_OWNER_ID]);if(!goal.rows[0]){res.status(404).json({error:'Goal not found.'});return;}if(!process.env.GROQ_API_KEY||!process.env.GROQ_MODEL){res.status(503).json({error:'AI is unavailable. You can define the outcome manually.',code:'ai_not_configured'});return;}res.status(200).json({suggestion:await suggest(goal.rows[0])});}catch(error){if(error instanceof GroqRequestError&&error.status===429){res.status(429).json({error:'AI request limit reached.',code:'ai_rate_limited'});return;}res.status(502).json({error:'AI suggestion unavailable. You can define the outcome manually.',code:'ai_unavailable'});}});
  return router;
}
export const outcomeRouter=createOutcomeRouter();
